name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode 12.3
      run: sudo xcode-select -s /Applications/Xcode_12.3.app

    - name: Build and Test
      run: xcodebuild clean build -sdk iphonesimulator
